### ISSUE TITLE
Need to add a parameter to set the cloud environment for Azure CLI to allow switching to non commercial clouds

### ISSUE THREAD

**Issue by wallenc** [Azure/avslabs#1]
In the bootstrap-nesteddeployment.ps1 file, there are several calls to

`az login --identity`

But, when calling az login, you are sent to the Azure Public cloud by default.
If you need to authenticate to a different cloud, such as AzureUsGovernment, you need to set the proper cloud in CLI prior to running az login. 
You can set the cloud with the following command:

`az cloud set --name AzureUsGovernment`

This should be made a parameter to allow for authentication to any non-commercial cloud environment

**Comment by husamhilal** [comment]
Thanks a lot @wallenc for creating this issue. It's a great suggestion and the team will handle it and make it available before the end of MSFT FY23 Q3.

**Comment by husamhilal** [comment]
I added the new support for MAG. The parameter to **isMAG** (or: **IsAzureGovernment**) can be used when executing bootstrap.ps1 or bootstrap-nestedlabs.ps1. It is a switch parameter, so if it exists then it the script will change the Cloud to AzureUsGovernment. 

It's a switch parameter, no need to provide value (such as $true or $false)

Next is to modify the bicep template to pass that parameter at the beginning of the deployment. 

@wallenc Thanks again for your help identifiying this gap.
