### ISSUE TITLE
Current version of the bootstrap-nestedlab.ps1 does not extract

### ISSUE THREAD

**Issue by starkilla2003** [Azure/avslabs#6]
The powershell script seems to be missing a "\" at the end of the path for extraction. When I run it only a file was created. After manuall adding the backslash it seems to be working.

Also in that instance the script pretends to run successfully. Maybe another check to fail gracefully is needed.

**Comment by husamhilal** [comment]
Thanks a lot Frank for the feedback 👍 Can you please confirm that? I used the automation not long ago, and I also know others used it, and they didn't have the issue.

**Comment by starkilla2003** [comment]
I had that issue last week. But sadly I changed the trailing backslash AND extended the C: disk because the default one is too small. 

Will try to confirm it again.

**Comment by husamhilal** [comment]
If you can point me please where the missing double quotes are, that would help 👍
